public class DeleteOldAccountRecords {
/*    
    public static void deleteAccountsOlderThan30Days() {
        Date thirtyDaysAgo = Date.today().addDays(-10);
        
        List<Account> accountsToDelete = [SELECT Id FROM Account WHERE CreatedDate < :thirtyDaysAgo];
        
        if (!accountsToDelete.isEmpty()) {
            delete accountsToDelete;
            System.debug('Old account records deleted successfully.');
        } else {
            System.debug('No old account records found.');
        }
    }*/
}