public class SOQLPRACTICE {
 /*   public static void myMethod()
    {
       list<contact>conList= [select id, name , phone from contact order by name asc limit 10 offset 5];
        system.debug('contactList' + conList);
        for(contact con :conList)
        {
            system.debug('conList' +con);
        }
    } 
   public static void myMethod2()
   {
        "%" (percentage) zero or more character
        "_" (Underscore)  represent only one character 
       list<account>accList= [select id , name , rating from account where name= 'a%' ];
       system.debug(accList);
   } */
}